with-expecter: true
filename: "{{.InterfaceName | snakecase }}.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/opencloud-eu/opencloud/pkg/keycloak:
        config:
            dir: "pkg/backends/keycloak/mocks"
        interfaces:
            Client:
