with-expecter: true
filename: "{{.InterfaceName | snakecase }}.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/opencloud-eu/opencloud/services/proxy/pkg/user/backend:
        config:
          dir: "pkg/user/backend/mocks"
        interfaces:
            UserBackend:
    github.com/opencloud-eu/opencloud/services/proxy/pkg/userroles:
        config:
          dir: "pkg/userroles/mocks"
        interfaces:
            UserRoleAssigner:
