with-expecter: true
filename: "{{.InterfaceName | snakecase }}.go"
dir: "{{.PackageName}}/mocks"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
    github.com/opencloud-eu/opencloud/pkg/oidc:
        interfaces:
            OIDCClient:
